### ISSUE TITLE
ReferenceError: app is not defined

### ISSUE THREAD

**Issue by 0x6a69616e** [0x6a69616e/snaptik-app#1]
```
ReferenceError: app is not defined
    at eval (eval at eval_script (/workspaces/snaptik-app/src/index.js:38:23), <anonymous>:3:300)
    at module.exports.eval_script (/workspaces/snaptik-app/src/index.js:38:140)
    at module.exports.process (/workspaces/snaptik-app/src/index.js:109:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by 0x6a69616e** [comment]
SnapTik embedded error handling within the obfuscated script, which triggers `app.showAlert()` when an error occurs. Should be fixed now!
